- name: PRELIM | Retrieve Default NTUSER and All Local User Hive Data
  block:
      - name: PRELIM | Load Default User Hive (Account That All New Users Get Created From Profile)
        ansible.windows.win_shell: REG LOAD HKU\DEFAULT C:\Users\Default\NTUSER.DAT
        changed_when: false
        failed_when: false

      - name: PRELIM | Pull All Username and SIDs
        ansible.windows.win_shell: Get-CimInstance -Class Win32_UserAccount -Filter "SID LIKE 'S-1-5-%'" | ForEach-Object { $_.Name + " " + $_.SID }
        changed_when: false
        failed_when: false
        register: all_users

      - name: PRELIM | Create Results List Fact For Username And SIDs
        ansible.builtin.set_fact:
            username_and_sid_results_list: "{{ all_users.stdout_lines | map('split', ' ') | list }}"

      - name: PRELIM | Load All User Hives From Username And SIDs List
        ansible.windows.win_shell: REG LOAD HKU\{{ item.1 }} C:\Users\{{ item.0 }}\NTUSER.DAT
        changed_when: false
        failed_when: false
        loop: "{{ username_and_sid_results_list }}"

      - name: PRELIM | Retrieve Current Users SIDs from HKEY_USERS
        ansible.windows.win_shell: (Get-ChildItem "REGISTRY::HKEY_USERS").name | Where-Object {$_ -notlike "*_classes"}
        changed_when: false
        failed_when: false
        register: current_users_loaded_hku

      - name: PRELIM | Create List Fact For Current Users SIDs from HKEY_USERS
        ansible.builtin.set_fact:
            hku_loaded_list: "{{ current_users_loaded_hku.stdout | regex_replace('HKEY_USERS\\\\','') | split }}"

- name: "19.1.3.1 | PATCH | Ensure Enable screen saver is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaveActive
      data: 1
      type: string
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.1.3.1
      - patch
      - screensaver

- name: "19.1.3.2 | PATCH | Ensure Password protect the screen saver is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaverIsSecure
      data: 1
      type: string
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.1.3.2
      - patch
      - screensaver

- name: "19.1.3.3 | PATCH | Ensure Screen saver timeout is set to Enabled 900 seconds or fewer but not 0"

  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Control Panel\Desktop
      name: ScreenSaveTimeOut
      data: 900
      type: string
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.1.3.3
      - patch
      - screensaver

- name: "19.5.1.1 | PATCH | Ensure Turn off toast notifications on the lock screen is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Currentversion\Pushnotifications
      name: NoToastApplicationNotificationOnLockScreen
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.5.1.1
      - patch
      - toast

- name: "19.6.6.1.1 | PATCH | Ensure Turn off Help Experience Improvement Program is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Assistance\Client\1.0
      name: NoImplicitFeedback
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.6.6.1.1
      - patch
      - help

- name: "19.7.4.1 | PATCH | Ensure Do not preserve zone information in file attachments is set to Disabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments
      name: SaveZoneInformation
      data: 2
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.4.1
      - patch
      - attachments

- name: "19.7.4.2 | PATCH | Ensure Notify antivirus programs when opening attachments is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\Currentversion\Policies\Attachments
      name: ScanWithAntiVirus
      data: 3
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.4.2
      - patch
      - antivirus

- name: "19.7.7.1 | PATCH | Ensure Configure Windows spotlight on lock screen is set to Disabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CloudContent
      name: ConfigureWindowsSpotlight
      data: 2
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.7.1
      - patch
      - cloudcontent

- name: "19.7.7.2 | PATCH | Ensure Do not suggest third-party content in Windows spotlight is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CloudContent
      name: DisableThirdPartySuggestions
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.7.2
      - patch
      - cloudcontent

- name: "19.7.7.3 | PATCH | Ensure Do not use diagnostic data for tailored experiences is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CloudContent
      name: DisableTailoredExperiencesWithDiagnosticData
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.7.3
      - patch
      - cloudcontent

- name: "19.7.7.4 | PATCH | Ensure Turn off all Windows spotlight features is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CloudContent
      name: DisableWindowsSpotlightFeatures
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.7.4
      - patch
      - cloudcontent

- name: "19.7.7.5 | PATCH | Ensure Turn off Spotlight collection on Desktop is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\CloudContent
      name: DisableSpotlightCollectionOnDesktop
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.7.5
      - patch
      - cloudcontent

- name: "19.7.25.1 | PATCH | Ensure Prevent users from sharing files within their profile. is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Microsoft\Windows\Currentversion\Policies\Explorer
      name: NoInplaceSharing
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.25.1
      - patch
      - profiles
      - sharing

- name: "19.7.40.1 | PATCH | Ensure Always install with elevated privileges is set to Disabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windows\Installer
      name: AlwaysInstallElevated
      data: 0
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.40.1
      - patch
      - permissions

- name: "19.7.42.2.1 | PATCH | Ensure Prevent Codec Download is set to Enabled"
  ansible.windows.win_regedit:
      path: HKU:\{{ item }}\SOFTWARE\Policies\Microsoft\Windowsmediaplayer
      name: PreventCodecDownload
      data: 1
      type: dword
  loop: "{{ hku_loaded_list }}"
  tags:
      - rule_19.7.42.2.1
      - patch
      - codec
